// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwdA3P0ZhJZHVhFroptsRxt6IxvqMj4zk',
    appId: '1:716571303887:android:ae70040f1d8aa28f6f7cba',
    messagingSenderId: '716571303887',
    projectId: 'abigail-c7d46',
    databaseURL: 'https://abigail-c7d46-default-rtdb.firebaseio.com',
    storageBucket: 'abigail-c7d46.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmspc2sJntbVpLrBFTwTADY47JFkR8kJ8',
    appId: '1:716571303887:ios:87e642f42ad834e56f7cba',
    messagingSenderId: '716571303887',
    projectId: 'abigail-c7d46',
    databaseURL: 'https://abigail-c7d46-default-rtdb.firebaseio.com',
    storageBucket: 'abigail-c7d46.appspot.com',
    iosClientId: '716571303887-uts59f1ejg8hje5ih690bipaartmpt6e.apps.googleusercontent.com',
    iosBundleId: 'com.abigail.abigail',
  );
}
